### ISSUE TITLE
Web Page

### ISSUE THREAD

**Issue by DiegoRBaquero** [jasalo/funcssion#1]
- ~~Use all 12 columns for the first text~~
- [x] https and CDN in link
- [x] Favicon
- [ ] Footer

**Comment by jasalo** [comment]
HTTPS is working now and CDN is "sort of" available, as I'm using CloudFlare, but I'd still rather have it available at CDNJS.

**Comment by jasalo** [comment]
Favicon done.

**Comment by trustice29** [comment]
your link on the website to pure functions in wiki is https://en.wikipedia.org/wiki/Pure_function), better remove the ) to link the correct wiki page :)

**Comment by jasalo** [comment]
Fixed it @trustice29 
Thanks!

**Comment by jackmcpickle** [comment]
Are you able to publish to npm too please. Then you can use https://unpkg.com/#/ to use as a cdn for the src sass file?

**Comment by jasalo** [comment]
@jackmcpickle Yeah, I'll work on that during the weekend :)
